package executor

import (
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/VeloraDEX/velora-dex-lib/txbuilder/resolved"
)

// The golden fixtures are bytecode built by the TS Executor01/02 builders on
// a fixed scenario matrix covering the revertable fallback group: layout,
// end-state alignments, input/output normalization, and the mid-route guard.
// Generated by paraswap-dex-lib/src/executor/generate-fallback-goldens.test.ts
// (the header records the TS commit); this test proves the Go builders emit
// the same bytes on the same inputs.

type fallbackGoldenFile struct {
	TsCommit  string                   `json:"tsCommit"`
	Context   fallbackGoldenContext    `json:"context"`
	Scenarios []fallbackGoldenScenario `json:"scenarios"`
}

type fallbackGoldenContext struct {
	Network                   int              `json:"network"`
	AugustusV6Address         resolved.Address `json:"augustusV6Address"`
	WrappedNativeTokenAddress resolved.Address `json:"wrappedNativeTokenAddress"`
}

type fallbackGoldenScenario struct {
	Name              string                           `json:"name"`
	Executor          string                           `json:"executor"`
	PriceRoute        fallbackGoldenRoute              `json:"priceRoute"`
	ExchangeParams    []resolved.DexExchangeBuildParam `json:"exchangeParams"`
	MaybeWethCallData *resolved.WethPlan               `json:"maybeWethCallData"`
	Bytecode          resolved.HexBytes                `json:"bytecode"`
}

type fallbackGoldenRoute struct {
	SrcToken   resolved.Address          `json:"srcToken"`
	DestToken  resolved.Address          `json:"destToken"`
	DestAmount resolved.DecimalString    `json:"destAmount"`
	BestRoute  []resolved.RoutePlanRoute `json:"bestRoute"`
}

func TestFallbackGroupTSParity(t *testing.T) {
	raw, err := os.ReadFile("testdata/fallback_goldens.json")
	if err != nil {
		t.Fatalf("read golden fixtures: %v", err)
	}
	var goldens fallbackGoldenFile
	if err := json.Unmarshal(raw, &goldens); err != nil {
		t.Fatalf("decode golden fixtures: %v", err)
	}
	if len(goldens.Scenarios) == 0 {
		t.Fatal("golden fixture file carries no scenarios")
	}

	context := resolved.EncodingContext{
		Network:                   goldens.Context.Network,
		AugustusV6Address:         goldens.Context.AugustusV6Address,
		WrappedNativeTokenAddress: goldens.Context.WrappedNativeTokenAddress,
	}

	for _, scenario := range goldens.Scenarios {
		t.Run(scenario.Name, func(t *testing.T) {
			priceRoute := executorRoute{
				SrcToken:   scenario.PriceRoute.SrcToken,
				DestToken:  scenario.PriceRoute.DestToken,
				DestAmount: scenario.PriceRoute.DestAmount,
				BestRoute:  scenario.PriceRoute.BestRoute,
			}
			input := testBytecodeBuildInput(priceRoute, scenario.ExchangeParams)
			input.WethPlan = scenario.MaybeWethCallData

			var bytecode resolved.HexBytes
			var err error
			switch scenario.Executor {
			case "Executor01":
				bytecode, err = NewExecutor01Builder(context).BuildBytecode(input)
			case "Executor02":
				bytecode, err = NewExecutor02Builder(context).BuildBytecode(input)
			default:
				t.Fatalf("unknown executor %q", scenario.Executor)
			}
			if err != nil {
				t.Fatalf("BuildBytecode() error = %v", err)
			}

			want := strings.ToLower(string(scenario.Bytecode))
			if got := strings.ToLower(string(bytecode)); got != want {
				t.Errorf("bytecode diverges from the TS builder (tsCommit %s)\n got: %s\nwant: %s",
					goldens.TsCommit, got, want)
			}
		})
	}
}
